//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Koebt
{
    public int Id { get; set; }
    public int UserId { get; set; }
    public int WishlistId { get; set; }
    public string Amount { get; set; }

    public virtual User User { get; set; }
    public virtual Wishlist Wishlist { get; set; }
}

public partial class User
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public User()
    {
        this.Koebts = new HashSet<Koebt>();
    }

    public int Id { get; set; }
    public string UserName { get; set; }
    public string Password { get; set; }
    public string Email { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public Nullable<System.DateTime> LastLoginDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Koebt> Koebts { get; set; }
}

public partial class Wishlist
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Wishlist()
    {
        this.Koebts = new HashSet<Koebt>();
    }

    public int Id { get; set; }
    public string Navn { get; set; }
    public string Link { get; set; }
    public bool Koebt { get; set; }
    public int Vaerdi { get; set; }
    public int VaerdiKoebt { get; set; }
    public string VaerdiEnhed { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Koebt> Koebts { get; set; }
}
